### ISSUE TITLE
Turn off the timer0

### ISSUE THREAD

**Issue by alessio31183** [thomasonw/ATmegaCAN#16]
I've found an issue on using this platform.
If I turn off the timer0 with the instruction Turn off the TCCR0B = 0 nothing works.

Any suggestion?

**Comment by thomasonw** [comment]
IIRC, TIMER-0 is used for the heart-beat, ala millis() , but also other internal timing related functions.   I suspect if you turn it off some of the Arduino CORE files will be caught in an infinite loop waiting for a timeout to occur.

**Comment by alessio31183** [comment]
Yes I've found that the timer0 is always on for some arduino tick count.
Timer0 is set in the wiring.c inside the arduino core folder

**Comment by thomasonw** [comment]
Ya, I think you will find Timer-0 is rather critical to the whole Arduino approach.  Any specific reason you are looking to turn it off?

**Comment by alessio31183** [comment]
Because I had an idea that it turns on the uC sleep mode.

Anyway solved.

Thanks

**Comment by thomasonw** [comment]
ok,
