### ISSUE TITLE
I2C and SPI protocoles

### ISSUE THREAD

**Issue by ghost** [thomasonw/ATmegaCAN#17]
Hi Thomas!
First of all, congratulations for your API, it is a great job.
But, I would like to know if I can use SPI or I2C libraries using the ATMegaxxM1 with arduino IDE.
Thanks in advance.

**Comment by thomasonw** [comment]
I have used the soft I2C lib, have not tried the SPI - however it is the same as the standard Arduino, so suspect it would work fine.
