### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by FalconFour** [thomasonw/ATmegaCAN#24]
Was just telling a friend about this repo & the awesome power of the ATmegaxxM1-C1 series chips... and I noticed a typo in the repo description:

`CAN enabled Amtel AVR chips`

Tiny little thing, but Atmel** 😄 

Easy issues are the best, aren't they?

**Comment by thomasonw** [comment]
@FalconFour   LOL, Yes they are!   Thanks for the note, make the change.   Ha, maybe should read 'Microchip' now?  <SMILE>

**Comment by thomasonw** [comment]
Closing

**Comment by thomasonw** [comment]
@FalconFour LOL, Yes they are! Thanks for the note, make the change. Ha, maybe should read 'Microchip' now?
